#!/bin/bash

# Путь к файлу Python скрипта
python_script="$HOME/drs/drs_wx"

# Путь к  DB
directory="$HOME/Documents/db.db"

# Проверяем наличие файла
if [ -f "$directory" ]; then
    "$python_script" -c "$directory"
else
    echo "Файл $directory не найден."
fi
